title: "Convergent: Local File Converter Utility"
description: "Fast, local batch file converter CLI for audio, video, images, and documents powered by FFmpeg and ImageMagick."
theme: jekyll-theme-primer
google_site_verification: "GEk2xgoHNJ_dvaDxAXEzyjO8W9PtYNC-xsu0CNspahA"
